world_map =  {
	-2: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I                                                                  ',
		'P                                   G                              ',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX  X  X  XX   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXttXXttXttXttXXtttXtttXttXXttXttXttXttX X  X  X  X  X  X  X  X  X  '

	],
	-1: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I                                                                  ',
		'P                                   G                              ',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX XX  X  X  X X   X   X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXtXXttXttXttXtXtttXtttXttXXttXttXttXttX X  X  X  X  X  X  X  X  X  '

	],
	0 : [
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'                                                                   ',
	'I      ccc     cc    cc     ccc     c                                ',
	'P                                    G                              ',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X'
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
    'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X'
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XX  XXX   X  XX  X  X  XX  X   XX  X X  X  X  X  X  X  X  X  X  X  X  X',
	'XXttXXXtttXttXXttXttXttXXttXtttXXttXtXttXttX X  X  X  X  X  X  X  X  X ',


],
	1: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I     ccc    ccc      cc     cc    cc                                 ',
		'P                                    G                                ',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX  XX   X  X   XX   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXttXXtttXttXtttXXtttXttXttXXttXttXttXttX X  X  X  X  X  X  X  X  X  '

	],
	2: [
		'                                       ',
		'                                       ',
		'                                       ',
		'                                       ',
		'                                       ',
		'                                       ',
		'                                       ',
		'                                       ',
		'I     ccc     ccc    cc      cc    cc        ',
		'P                                    G   ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
        'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XX  XX   X  XX   X  X  XX   X  XX X  X  X  ',
		'XXttXXtttXttXXtttXttXttXXtttXttXXtXttXttX ',

	],
	3: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I     ccc     cc    ccc     cc     cc                             ',
		'P                                    G                             ',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
        'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXX  X   X  XX  X  X   XX  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXXttXtttXttXXttXttXtttXXttXttXXttXttXttXttX X  X  X  X  X  X  X  X  X ',

	],
	4: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I  cc     c      cc     cc     cc                                     ',
		'P                                   G                                 ',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
        'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X  X  XX  X   X  X  XX  X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXtttXtttXttXttXXttXtttXttXttXXttXttXttXttX X  X  X  X  X  X  X  X  X ',

	],
	5: [
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'                                                                   ',
		'I     ccc     cc     cc    ccc    cc                                 ',
		'P                                    G                                ',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XX   X   X   X  X   X  X  X   X  X   X  X  X  X  X  X  X  X  X  X  X  X  X',
		'XXtttXtttXtttXttXtttXttXttXtttXttXtttXttXttXttXttX X  X  X  X  X  X  X  XX',

	],
}
map_sizex, map_sizey = 66, 10
tile_size = 50
level = 0
